mode: auto

favicon: https://cdn.jsdelivr.net/gh/Rotten-LKZ/cdn@main/images/basic/avatar-icon-39e68a.png

avatar:
  url: https://cdn.jsdelivr.net/gh/Rotten-LKZ/cdn@main/images/basic/avatar-7f23ce.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: å¯¹é…’å½“æ­Œï¼Œäººç”Ÿå‡ ä½•ï¼Ÿ

reward:
  enable: true
  comment: å‘±å‘±å‘±~~å’£å•·å’£å•·å’£å•·~~~ï¼ˆèµåŠ©ï¼‰
  methods:
    - name: æ”¯ä»˜å®
      path: https://cdn.jsdelivr.net/gh/Rotten-LKZ/cdn@main/images/basic/donation-code/alipay-3d7782.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: QQ æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/Rotten-LKZ/cdn@main/images/basic/donation-code/qq-607995.jpg
      color: "#12B7F5"
      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/Rotten-LKZ/cdn@main/images/basic/donation-code/wechat-60f837.jpg
      color: "#2DC100"
      icon: icon-wechat-pay-line

comment:
  candidates:
    - waline
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://jq.qq.com/?_wv=1027&k=BzFZqGhH" target="_blank">QQ ç¾¤ 836523771</a> ä¸æˆ‘äº¤æµã€‚

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false

# https://github.com/laymonage/giscus
giscus:
  enable: false

footer:
  since: 2022
  # icon:
  #   url: https://sponsors.yunyoujun.cn
  #   title: äº‘æ¸¸å›çš„èµåŠ©è€…ä»¬
  support:
    enable: true
    title: åˆæ‹äº‘
    link: https://www.upyun.com
    logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: æœ¬ç½‘ç«™ç”±
    suffix: æä¾› CDN åŠ é€Ÿå’Œäº‘å­˜å‚¨æœåŠ¡
#  custom_text:
  live_time:
    enable: false
    prefix: æœ¬ç½‘ç«™å·²å¼€å§‹è®°å½•
    suffix: å¤©æˆ‘çš„ç”Ÿæ´»
    start_time: "2022-03-13T23:09:00"

engine_search:
  enable: false

google_analytics:
  enable: true
  id: G-1LL0D86CY9

google_adsense:
  enable: true
  client: ca-pub-2245427233262012

post_edit:
  enable: false

albums:
  enable: true

girls:
  enable: true

# tags:
  # åŠ¨ç”»: crimson
  # æ¼«ç”»: orange
  # Parcel: "#21374b"
  # å­¦ä¹ : saddlebrown
  # MAD: crimson
  # æ•™ç¨‹: royalblue
  # ç¬”è®°: dimgray
  # åˆ†äº«: "#0078e7"
  # éšç¬”: mediumpurple
  # Blender: "#d04d2d"
  # Linux: "#2577b1"
  # ä¸­ä¼ : "#ccb44b"
  # éƒ¨è½: "#DD306A"
  # ç§‘å¹»: midnightblue
  # èš‚èšæ£®æ—: "#54a892"

# categories:
  # äº‘æ¸¸çš„å°è§†é¢‘: "#FB7299"

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  # - name: å–œæ¬¢çš„å¥³å­©å­
  #   url: /girls/
  #   icon: icon-women-line
  #   color: hotpink

menu:
  custom:
    title: å…³äºæˆ‘
    path: /about/
    icon: icon-clipboard-line

cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: true
  id: GTM-M9KWR9L

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: QQ ç¾¤ 836523771
    link: https://jq.qq.com/?_wv=1027&k=BzFZqGhH
    icon: icon-qq-line
    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/Rotten-LKZ
    icon: icon-github-line
    color: "#6e5494"
  - name: å¾®åš
    link: https://weibo.com/rottenlkz
    icon: icon-weibo-line
    color: "#E6162D"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=634683704
    icon: icon-netease-cloud-music-line
    color: "#C20C0C"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/rotcool
    icon: icon-zhihu-line
    color: "#0084FF"
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/290238250
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: E-Mail
    link: mailto:rotten_lkz@outlook.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: Travelling
    link: https://travellings.link
    icon: icon-train-line
    color: black

banner:
  enable: true
  title: çƒ‚è£¤å­ã®æ—¥å¸¸
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

notice:
  enable: false
  content: Test
